# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.10' # 指定 Python 版本

# 设置 Python 环境
sphinx:
  configuration: docs/conf.py # 指定 Sphinx 配置文件路径
  fail_on_warning: false # 可选：警告是否视为构建失败

# 安装项目依赖（如果需要）
python:
  install:
    - requirements: docs/requirements.txt # 从文件安装依赖
    - method: pip
      path: . # 如果根目录有 setup.py/pyproject.toml 可自动安装包

# 安装系统级依赖（可选）
# build:
#   apt_packages:
#     - libgeos-dev  # 示例：系统库依赖

# 自定义构建命令（可选）
# build:
#   commands:
#     - make -C docs clean html  # 手动调用构建命令

# 其他可选配置
formats: # 输出格式（默认已包含html）
  - html
  # - pdf   # 如需生成 PDF
  # - epub
# 环境变量（可选）
# build:
#   environment:
#     YOUR_ENV_VAR: "value"
