language: python
sudo: enabled
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- nightly
- pypy
- pypy3
env:
  global:
  - CODECOV_TOKEN="b5b63c88-6a8f-4858-aac1-d0da33bd5c9d"
  - FLASK_PLUGINKIT_TEST_REDISURL="redis://@localhost"
  matrix:
  - FLASK_VERSION=0.9
  - FLASK_VERSION=0.10
  - FLASK_VERSION=0.11
  - FLASK_VERSION=0.12
  - FLASK_VERSION=1.0
  - FLASK_VERSION=1.1.0
matrix:
  exclude:
  - python: '3.5'
    env: FLASK_VERSION=0.9
  - python: '3.6'
    env: FLASK_VERSION=0.9
  - python: '3.7'
    env: FLASK_VERSION=0.9
  - python: pypy3
    env: FLASK_VERSION=0.9
  - python: pypy3
    env: FLASK_VERSION=0.11
  allow_failures:
  - python: nightly
services:
- redis-server
install:
- pip install -U -r dev-requirements.txt
- pip install redis
- pip install git+https://github.com/saintic/flask-pluginkit-demo@master#egg=flask-pluginkit-demo
- pip install Flask==$FLASK_VERSION
- make dev
script:
- coverage run setup.py test
after_success:
- codecov
deploy:
  provider: pypi
  user: saintic
  password:
    secure: xr/5VfQWftfjcd4djqUaXgC4V9qxRA2nLRkgX/gDnDaPJ8JL04JqNm8q/sF0p7YoIJZZUMbk/PJpaykZmOTzEpwT4bDKRWxlMEDOO+H/JsSD2Eoll9LNygAnb/MBWkqIfZn8gAQJuegc7luCTT0Ha62gOdAnQIDwF9zwCP50sA8yoPwlzPB/km1BFzQ5ZHLisCw43WCRIqBPB4/sgOxgVm8U5WDUVvhiTc3Lh2oKxEcCeR7NVbMd3bbcomOrHwhicTDRiUNJmIqpjM/2rhf+JsfPjJjnGdrE1EeVRGbplnFzCJbeOLU2O8Ol9VROJ+5JTZ1Y2JEHjyDS41NW/LXmhMUX9s2ivgWFfvWRZ0XAoKo5WTHhY23E5ERlujsqgERNKgBciZQnKvTLzhM8NABsihYpf35eCJf/4hJ8re6QgtdHzR+4eTJG+n42RDPJgzeCgEeaxsrei7xiYa3aMNLZ+DpWS+Uo6q7F6tiMYqzspvaCCNOoj0N1AeF1PBUfFy8Gm18aoDO17iF7IOrpiiBE8PKjjgwT0lNjNG+ivSPGlh+E1BiWfhdX34+MTzSvE3uFTOjiCJL5TzBLJi5KwteR0Opla4LIzrcDJiy25yz+24kwuSmTIX2uENXnjvENPkHXfI+NopSqAguFOQFcUBMT0aC/FykQ/nfR5tau0GyPAAo=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    python: 2.7
    condition: "$FLASK_VERSION = 1.0"
    tags: true
    branch: master
